### ISSUE TITLE
LuisaCompute 404?

### ISSUE THREAD

**Issue by ccworld1000** [LuisaGroup/LuisaRender#1]
LuisaCompute 404?

**Comment by Mike-Leo-Smith** [comment]
LuisaCompute is currently under massive refactoring, so we made it private.

**Comment by Nolram12345** [comment]
This problem still persist and makes it impossible to build the renderer.

**Comment by Mike-Leo-Smith** [comment]
We are planning to make LuisaCompute public again in the next month or two. Please wait.

**Comment by Mike-Leo-Smith** [comment]
Sorry for the long delay.

LuisaCompute and all applications are now officially public!
