### ISSUE TITLE
无法打开输入文件“..\base\Release\luisa-render-base.lib”

### ISSUE THREAD

**Issue by qaz123w** [LuisaGroup/LuisaRender#11]
![image](https://user-images.githubusercontent.com/75780167/230777648-77440046-d739-4991-9298-65c739ce1b2e.png)

**Comment by qaz123w** [comment]
应该是luisa-render-base有问题，单独生成luisa-render-base是这样
![image](https://user-images.githubusercontent.com/75780167/230777927-331a1185-48a4-4a90-b4de-c2281c0b56c1.png)
提示缺少文件，但实际上有的
![image](https://user-images.githubusercontent.com/75780167/230777993-e8373e84-e7e7-44a3-a82a-08ef4ada43e5.png)
![image](https://user-images.githubusercontent.com/75780167/230778054-08f499c5-c428-4c29-a276-a0ab1d5e14d8.png)

**Comment by Mike-Leo-Smith** [comment]
从图上看，你应该使用了LuisaCompute-next分支，但目前LuisaRender依赖LuisaCompute-master，尝试重新克隆。

**Comment by qaz123w** [comment]
原来是这样，谢谢
