### ISSUE TITLE
-- Checking for module 'zzip-zlib-config' --   No package 'zzip-zlib-config' found

### ISSUE THREAD

**Issue by disini** [LuisaGroup/LuisaRender#15]
Hello Sir,

I'm trying to compile this project on ubuntu 22.04.2, with cuda 12.2 and optix 7.7, and using a intel 6700k cpu and gtx 1070 gpu.
I fixed some errors before by installing and updating the rust tool chain, and when I execute cmake, it was done with some warnings :

```
-- Shared libraries enabled
-- Looking for ZLIB...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'zzip-zlib-config'
--   No package 'zzip-zlib-config' found
-- Found ZLIB: optimized;/usr/lib/x86_64-linux-gnu/libz.so;debug;/usr/lib/x86_64-linux-gnu/libz.so
-- Checking for module 'minizip'
--   Found minizip, version 4.0.0
```

I searched that warning on google and bing, and asked my gpt and it suggests me to execute :

```
sudo apt update
sudo apt install libzzip-dev
```

and I've done that already for several times and I'm sure the zlib was installed correctly.

the entire cmake log is as below:

```

uisaGroup/LuisaRender/LuisaRender/build_ubuntu# cmake ../
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build with sccache: /root/.cargo/bin/sccache
-- Shared libraries enabled
-- Looking for ZLIB...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'zzip-zlib-config'
--   No package 'zzip-zlib-config' found
-- Found ZLIB: optimized;/usr/lib/x86_64-linux-gnu/libz.so;debug;/usr/lib/x86_64-linux-gnu/libz.so
-- Checking for module 'minizip'
--   Found minizip, version 4.0.0
-- Build an import-only version of Assimp.
-- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IQM IRR LWO LWS M3D MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled importer formats:
-- Treating all warnings as errors (for assimp library only)
CMake Warning at src/compute/scripts/validate_options.cmake:42 (message):
  The DirectX backend is not available.  The DirectX backend will be
  disabled.
Call Stack (most recent call first):
  src/compute/scripts/validate_options.cmake:51 (report_feature_not_available)
  src/compute/CMakeLists.txt:43 (include)


CMake Warning at src/compute/scripts/validate_options.cmake:42 (message):
  The Metal backend is not available.  The Metal backend will be disabled.
Call Stack (most recent call first):
  src/compute/scripts/validate_options.cmake:57 (report_feature_not_available)
  src/compute/CMakeLists.txt:43 (include)


-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Build with sccache: /root/.cargo/bin/sccache
-- Build spdlog: 1.11.0
-- Build type: Release
-- Including X11 support
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Performing Test EASTL_HAS_FCHAR8T_FLAG
-- Performing Test EASTL_HAS_FCHAR8T_FLAG - Success
-- Performing Test EASTL_HAS_ZCCHAR8T_FLAG
-- Performing Test EASTL_HAS_ZCCHAR8T_FLAG - Failed
CMake Deprecation Warning at src/compute/src/ext/EASTL/packages/EABase/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Rust Toolchain: stable-x86_64-unknown-linux-gnu
-- Rust Target: x86_64-unknown-linux-gnu
-- Determining required link libraries for target x86_64-unknown-linux-gnu
-- Required static libs for target x86_64-unknown-linux-gnu: gcc_s;util;rt;pthread;m;dl;c
-- Found Rust: /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc (found version "1.71.0") 
-- Using Corrosion as a subdirectory
-- Found Vulkan: /usr/lib/x86_64-linux-gnu/libvulkan.so (found version "1.3.250") found components: glslc glslangValidator 
-- Found CUDAToolkit: /usr/local/cuda/include (found suitable version "12.2.91", minimum required is "11.7") 
-- Build with CUDA backend: 12.2.91
-- Downloading nvcomp from https://developer.download.nvidia.com/compute/nvcomp/2.6.1/local_installers/nvcomp_2.6.1_x86_64_12.x.tgz
-- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.91") 
-- Found nvcomp: /media/liusheng/Projects/project/game_engines/LuisaRender/github/LuisaGroup/LuisaRender/LuisaRender/build_ubuntu/_deps/nvcomp-src/lib/cmake/nvcomp/nvcomp-config.cmake (found version "2.6.1") 
-- Configuring done (5.4s)
-- Generating done (1.8s)
-- Build files have been written to: /media/liusheng/Projects/project/game_engines/LuisaRender/github/LuisaGroup/LuisaRender/LuisaRender/build_ubuntu
```

and it didn't give more tips about that warning, so I'm really confused.......

How should I fixed that ?  Thanks!

**Comment by Mike-Leo-Smith** [comment]
> CMake Warning at src/compute/scripts/validate_options.cmake:42 (message):
>   The DirectX backend is not available.  The DirectX backend will be
>   disabled.
> Call Stack (most recent call first):
>   src/compute/scripts/validate_options.cmake:51 (report_feature_not_available)
>   src/compute/CMakeLists.txt:43 (include)
> 
> 
> CMake Warning at src/compute/scripts/validate_options.cmake:42 (message):
>   The Metal backend is not available.  The Metal backend will be disabled.
> Call Stack (most recent call first):
>   src/compute/scripts/validate_options.cmake:57 (report_feature_not_available)
>   src/compute/CMakeLists.txt:43 (include)

These warnings should be just fine. LuisaCompute by default enables all backends and warns you if some of them are not available on your platform. You may make a copy of `scripts/options.cmake.template` to `scripts/options.cmake` and specify exactly the features you want if these warnings bother you :-)

**Comment by disini** [comment]
Thank your sir, 'm not talking about those two warnings about backend, I'm running it on unbuntu so there's definitely no DirectX and Metal on it, what bothered me a little is the warning on the title of this page, 

"-- Checking for module 'zzip-zlib-config' -- No package 'zzip-zlib-config' found"

I really can't find anything about that warning, can you reproduce that on your own computer?

Thanks so much!

**Comment by Mike-Leo-Smith** [comment]
> Thank your sir, 'm not talking about those two warnings about backend, I'm running it on unbuntu so there's definitely no DirectX and Metal on it, what bothered me a little is the warning on the title of this page,
> 
> "-- Checking for module 'zzip-zlib-config' -- No package 'zzip-zlib-config' found"

This message is produced by [assimp](https://github.com/assimp/assimp). I think it's just informing you that it could not find the `zzip` library and thus turned to the standard `zip` library, as the following lines say.

Should be fine just to ignore it as well :-)

**Comment by disini** [comment]
> > Thank your sir, 'm not talking about those two warnings about backend, I'm running it on unbuntu so there's definitely no DirectX and Metal on it, what bothered me a little is the warning on the title of this page,
> > "-- Checking for module 'zzip-zlib-config' -- No package 'zzip-zlib-config' found"
> 
> This message is produced by [assimp](https://github.com/assimp/assimp). I think it's just informing you that it could not find the `zzip` library and thus turned to the standard `zip` library, as the following lines say.
> 
> Should be fine just to ignore it as well :-)

OK, Thanks so much! ^_^

**Comment by Mike-Leo-Smith** [comment]
Thank you!
