### ISSUE TITLE
Save save GPT

### ISSUE THREAD

**Issue by shiinamiyuki** [LuisaGroup/LuisaRender#19]
**Is your feature request related to a problem? Please describe.**
GPT is broken😡😡😡 @Mike-Leo-Smith 
 
**Describe the solution you'd like**
Fix it! 😡😡😡@Mike-Leo-Smith 

**Describe alternatives you've considered**
There is no other way 😡😡😡

**Additional context**
😡😡😡

**Comment by shiinamiyuki** [comment]
@Mike-Leo-Smith I mean depending on the workload this might not be the top priority though.

**Comment by Mike-Leo-Smith** [comment]
Saved. Still MUCH slower than PT tho.
