### ISSUE TITLE
Falling back to ad-hoc allocation

### ISSUE THREAD

**Issue by MaxwellFang** [LuisaGroup/LuisaRender#20]
**Describe the bug**
When running, this warning shows on the output:
 [warning] Failed to allocate x bytes from CUDAHostBufferPool. Falling back to ad-hoc allocation.

**Expected behavior**
Warning free I guess

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Driver: 535.113.01
 - CUDA version: 1.2.2
 - GPU: RTX 2080Ti

**Additional context**
Just curious why this warning appears

**Comment by Mike-Leo-Smith** [comment]
Yes it’s fine to have this warning.

We use a 64M staging buffer pool to reduce the allocation overhead of pinned memory, which is used in buffer uploading/downloading. If the concurrent data transfer between the CPU and GPU exceeds this 64M pool size, we then have to allocate non-pooled ad-hoc memory, hence the performance warning.

In LuisaRender, this might occur when uploading large meshes to, or downloading large frame buffers from the GPU, but both do not happen frequently. So it should be safe just to ignore this warning.

**Comment by MaxwellFang** [comment]
Thank you, I will close this issue then
