### ISSUE TITLE
Compiling error "reference to local binding 'basis' declared in enclosing function 'luisa::compute::metal::MetalCurve::build'"

### ISSUE THREAD

**Issue by Meowuu7** [LuisaGroup/LuisaRender#22]
**Describe the bug**
Building error

**To Reproduce**

I run into this problem when I tried to compile the project on maxOS 13 M2 silicon:
![Screenshot 2023-12-04 at 01 03 13](https://github.com/LuisaGroup/LuisaRender/assets/50799886/a09f949f-3d04-4849-9f61-2724ff3f11f3)

**Desktop (please complete the following information):**
 - OS: maxOS 13 M2 silicon

**Comment by Meowuu7** [comment]
The compiling is successful in a Ubuntu 20.04 environment. But I encountered with the "CUDA not support" issue when I tried to render a scene using the command 
```bash
./build/bin/luisa-render-cli  -b 'CUDA' ./data/bathroom/scene.luisa
```
![Screenshot 2023-12-04 at 01 09 53](https://github.com/LuisaGroup/LuisaRender/assets/50799886/4d19fef9-11de-4a68-88c0-460a8a8a39bc)

**Comment by Mike-Leo-Smith** [comment]
> **Describe the bug** Building error
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> I run into this problem when I tried to compile the project on maxOS 13 M2 silicon: ![Screenshot 2023-12-04 at 01 03 13](https://private-user-images.githubusercontent.com/50799886/287535891-a09f949f-3d04-4849-9f61-2724ff3f11f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2Nzg1ODUsIm5iZiI6MTcwMTY3ODI4NSwicGF0aCI6Ii81MDc5OTg4Ni8yODc1MzU4OTEtYTA5Zjk0OWYtM2QwNC00ODQ5LTlmNjEtMjcyNGZmM2YxMWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA4MjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YzA1YzFjY2IyNTZmYmM0MzIzY2Q0Njc2MjY2N2M5MjViMzhiMjY2NTQ1NjIzMWIwOGMwZDMzOTU4Mzg2ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8bP0THrxgEeszqPW7M5PSzIGMJD2FtUuQamy7YHtpgk)
> 
> **Desktop (please complete the following information):**
> 
> * OS: maxOS 13 M2 silicon

Previous versions of `clang` has trouble capturing structural bindings in lambdas. I have worked around this in a recent version of `LuisaCompute` and just now pushed a submodule update to `LuisaRender`.

Please use
```shell
git pull
git submodule update --recursive --init
```
to pull and apply the fix.

**Comment by Mike-Leo-Smith** [comment]
> The compiling is successful in a Ubuntu 20.04 environment. But I encountered with the "CUDA not support" issue when I tried to render a scene using the command
> 
> ```shell
> ./build/bin/luisa-render-cli  -b 'CUDA' ./data/bathroom/scene.luisa
> ```
> 
> ![Screenshot 2023-12-04 at 01 09 53](https://private-user-images.githubusercontent.com/50799886/287536200-4d19fef9-11de-4a68-88c0-460a8a8a39bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2Nzg1ODUsIm5iZiI6MTcwMTY3ODI4NSwicGF0aCI6Ii81MDc5OTg4Ni8yODc1MzYyMDAtNGQxOWZlZjktMTFkZS00YTY4LTg4YzAtNDYwYThhOGEzOWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA4MjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMjJiNDEzNzIzMTYwNTQwMWQ5YTJlNTczNWY4MzYyNGJjODVjOWZlNTc3ZDk4OTg1MTM4MTkzZTBhNmU2NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vlHkfmlq0Qh-pHO58s5aATpfUA-a3hDOSc9evnXAMq8)

Would you please run `nvidia-smi` to verify that your driver version is `535+`?

**Comment by Meowuu7** [comment]
The project can be successfully compiled by 

- upgrading `nvidia-smi` to `545`
- and using the latest commit.

Thank you for your help.
