### ISSUE TITLE
When I use Genesis. No module named 'LuisaRenderPy'

### ISSUE THREAD

**Issue by Xu-Xuanhui** [LuisaGroup/LuisaRender#31]
**Describe the bug**
When I use Genesis. No module named 'LuisaRenderPy'
python examples/rendering/demo.py

[Genesis] [23:14:40] [INFO] ╭───────────────────────────────────────────────╮
[Genesis] [23:14:40] [INFO] │┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈ Genesis ┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈│
[Genesis] [23:14:40] [INFO] ╰───────────────────────────────────────────────╯
[Genesis] [23:14:41] [INFO] Running on [NVIDIA GeForce RTX 4070 Laptop GPU] with backend gs.cuda. Device memory: 7.75 GB.
[Genesis] [23:14:42] [DEBUG] [Taichi] version 1.7.2, llvm 15.0.4, commit 0131dce9, linux, python 3.10.16
[Genesis] [23:14:42] [DEBUG] [Taichi] Starting on arch=cuda
[Genesis] [23:14:42] [INFO] 🚀 Genesis initialized. 🔖 version: 0.2.0, 🌱 seed: 0, 📏 precision: '32', 🐛 debug: False, 🎨 theme: 'dark'.
Traceback (most recent call last):
File "/home/xxh/anaconda3/envs/genesis/lib/python3.10/site-packages/genesis/vis/raytracer.py", line 17, in
import LuisaRenderPy
ModuleNotFoundError: No module named 'LuisaRenderPy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/xxh/Documents/Genesis-main/examples/rendering/demo.py", line 166, in
main()
File "/home/xxh/Documents/Genesis-main/examples/rendering/demo.py", line 11, in main
scene = gs.Scene(
File "/home/xxh/anaconda3/envs/genesis/lib/python3.10/site-packages/genesis/utils/misc.py", line 27, in new_init
original_init(self, *args, **kwargs)
File "/home/xxh/anaconda3/envs/genesis/lib/python3.10/site-packages/genesis/engine/scene.py", line 148, in init
self._visualizer = Visualizer(
File "/home/xxh/anaconda3/envs/genesis/lib/python3.10/site-packages/genesis/vis/visualizer.py", line 60, in init
from .raytracer import Raytracer
File "/home/xxh/anaconda3/envs/genesis/lib/python3.10/site-packages/genesis/vis/raytracer.py", line 19, in
gs.raise_exception(f"Failed to import LuisaRenderer. {e.class.name}: {e}")

[Genesis] [23:14:44] [ERROR] Failed to import LuisaRenderer. ModuleNotFoundError: No module named 'LuisaRenderPy'

It seems like python bindings are not being generated at all when luisa-render is compiled and built.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 24.04]

**Smartphone (please complete the following information):**
 - Device: [intel 14700 nvidia 4070]
 - OS: [Ubuntu 24.04]

**Additional context**

**Comment by Mike-Leo-Smith** [comment]
Hi, @Xu-Xuanhui 

Genesis uses a forked version of LuisaRender maintained by their project’s developers. You may have to wait for them to open-source it. Thank you!

**Comment by oscar-lima** [comment]
> Hi, @Xu-Xuanhui
> 
> Genesis uses a forked version of LuisaRender maintained by their project’s developers. You may have to wait for them to open-source it. Thank you!

Yeah... they use: https://github.com/Alif-01/LuisaRender

However the owner of that fork does not have issues enabled, see: https://stackoverflow.com/questions/16406180/is-there-a-way-to-add-issues-to-a-github-forked-repo-without-modifying-the-orig

which would be the appropriate place to put the issue IMO. Alternatively, it could be asked under genesis repo itself, e.g., see: https://github.com/Genesis-Embodied-AI/Genesis/issues/235

**Comment by oscar-lima** [comment]
Update: this issue was raised (and closed) already, see: https://github.com/Genesis-Embodied-AI/Genesis/issues/76 . IMO this can be closed now.

**Comment by Mike-Leo-Smith** [comment]
@oscar-lima Thank you for the info!

@Xu-Xuanhui I’ll close the issue now. Feel free to reopen it if you have any additional questions.
