### ISSUE TITLE
CMake build error, trying to build but facing the errors.

### ISSUE THREAD

**Issue by nixuser9** [LuisaGroup/LuisaRender#32]
**Describe the bug**
CMake build error, trying to build but facing the errors.

**To Reproduce**
1. Go to LuisaRender and build Cmake
2.  Below build error

```
[ 94%] Building CXX object src/integrators/CMakeFiles/luisa-render-integrator-nfor.dir/nfor.cpp.o
/home/nixuser/LuisaRender/src/integrators/nfor.cpp:103:5: error: ‘Framerate’ does not name a type
  103 |     Framerate _framerate;
      |     ^~~~~~~~~
/home/nixuser/LuisaRender/src/integrators/nfor.cpp: In member function ‘virtual void luisa::render::AuxiliaryBufferPathTracingInstance::render(luisa::compute::Stream&)’:
/home/nixuser/LuisaRender/src/integrators/nfor.cpp:124:13: error: ‘_framerate’ was not declared in this scope
  124 |             _framerate.clear();
      |             ^~~~~~~~~~
gmake[2]: *** [src/integrators/CMakeFiles/luisa-render-integrator-nfor.dir/build.make:76: src/integrators/CMakeFiles/luisa-render-integrator-nfor.dir/nfor.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:5359: src/integrators/CMakeFiles/luisa-render-integrator-nfor.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

```

**Expected behavior**

**Screenshots**
![Screenshot 2024-12-20 170245](https://github.com/user-attachments/assets/bdb88d75-feef-4dd9-b498-d4e8769ec22b)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**

**Comment by Mike-Leo-Smith** [comment]
Hi @mrmaverick9119 

I've added the missing `#include`. Please `git pull` and compile again to see if the issue is resolved.

Thank you!

**Comment by nixuser9** [comment]
Hi @Mike-Leo-Smith ,

Its building now, thank you for quick turnaround.

Best Regards !!
