### ISSUE TITLE
Is there any way to check the variable values of the DSL while debugging?

### ISSUE THREAD

**Issue by Riga27527** [LuisaGroup/LuisaRender#5]
I have no way to track the value of the variable after changing it to a DSL variable via **def** built-in functions. Is there a way to pass the DSL variable to the host?

**Comment by Mike-Leo-Smith** [comment]
Hi, @Riga27527

The DSL variables are created on the device and thus cannot be directly visited by the host code. To retrieve their values, generally, you would need to write them to a buffer, download it to a host memory, and then visit the host-side copy.
