### ISSUE TITLE
Is there a full version without "--recursive"?

### ISSUE THREAD

**Issue by HansenHuang0823** [LuisaGroup/LuisaRender#6]
When the network is unstable, "git clone --recursive" commands is likely to fail. Manually downloading these packages will take a lot of time. Can a full version be provided, with links to Baidu online disk or Google cloud disk?

**Comment by why986** [comment]
You can use `git submodule update --init --recursive` to fix the bug that some submodules may not be installed successfully after using `git clone --recursive`.

**Comment by Mike-Leo-Smith** [comment]
I uploaded a zip of commit [19a543b](https://github.com/LuisaGroup/LuisaRender/commit/19a543bbfcdb4b9c4af8812010f39a94b79ff1b4) here: https://cloud.tsinghua.edu.cn/f/8b7811774d1c4df2866a/?dl=1
