### ISSUE TITLE
Failed to build luisa-render-util due to std::endian

### ISSUE THREAD

**Issue by why986** [LuisaGroup/LuisaRender#8]
**Describe the bug**
I encounter a problem when I try to run the command `cmake --build build` to build the project. It seems to be a bug caused by c++20 compilation, but I am sure that my machine has a compiler (clang 14.0.0) that supports c++20 and is able to compile c++20 program. 
What's more, I wrote the follwoing codes to test whether my compiler can work when using std::endian:
```
#include<iostream>
#include<bit>
using namespace std;
int main()
{
# if __cplusplus > 201703L
	cout << "c++20 ok\n";
	if constexpr (std::endian::native == std::endian::big)
        std::cout << "big-endian\n";
    else if constexpr (std::endian::native == std::endian::little)
        std::cout << "little-endian\n";
    else std::cout << "mixed-endian\n";
# endif
	return 0;
}
```
I got the following output which seemed to prove the compiler can work when using std::endian
```
c++20 ok
little-endian
```

I would very appreciate your help!

**Environment**
- OS: MacOS 13.1 with M1 Pro
- cmake 3.25.1
- clang 14.0.0
- embree installed by brew

**Part of cmake logs**
```
[ 72%] Building CXX object src/util/CMakeFiles/luisa-render-util.dir/sampling.cpp.o
[ 72%] Building CXX object src/util/CMakeFiles/luisa-render-util.dir/frame.cpp.o
[ 72%] Building CXX object src/util/CMakeFiles/luisa-render-util.dir/imageio.cpp.o
[ 72%] Building CXX object src/util/CMakeFiles/luisa-render-util.dir/xform.cpp.o
[ 72%] Building CXX object src/util/CMakeFiles/luisa-render-util.dir/spec.cpp.o
[ 73%] Building CXX object src/util/CMakeFiles/luisa-render-util.dir/half.cpp.o
/Users/why/Desktop/LuisaRender/src/util/half.cpp:12:19: error: no member named 'endian' in namespace 'std'; did you mean 'eastl::endian'?
    static_assert(std::endian::native == std::endian::little,
                  ^~~~~~~~~~~
                  eastl::endian
/Users/why/Desktop/LuisaRender/src/compute/src/ext/EASTL/include/EASTL/type_traits.h:1030:13: note: 'eastl::endian' declared here
        enum class endian
                   ^
/Users/why/Desktop/LuisaRender/src/util/half.cpp:12:42: error: no member named 'endian' in namespace 'std'; did you mean 'eastl::endian'?
    static_assert(std::endian::native == std::endian::little,
                                         ^~~~~~~~~~~
                                         eastl::endian
/Users/why/Desktop/LuisaRender/src/compute/src/ext/EASTL/include/EASTL/type_traits.h:1030:13: note: 'eastl::endian' declared here
        enum class endian
                   ^
2 errors generated.
make[2]: *** [src/util/CMakeFiles/luisa-render-util.dir/half.cpp.o] Error 1
make[1]: *** [src/util/CMakeFiles/luisa-render-util.dir/all] Error 2
make: *** [all] Error 2
```

**Additional**
Also, when Linking CXX shared library ../libembree3.dylib, it report a lot of warnings like:
```
ld: warning: cannot export hidden symbol void embree::TaskScheduler::g_instance from ../libtasking.a(taskschedulerinternal.cpp.o)
```
I have no idea if this will have a bad influence in future running.

**Comment by Mike-Leo-Smith** [comment]
Fixed in [19a543b](https://github.com/LuisaGroup/LuisaRender/commit/19a543bbfcdb4b9c4af8812010f39a94b79ff1b4). It was because I forgot to `#include <endian>` in `src/util/half.cpp` :-(

**Comment by Mike-Leo-Smith** [comment]
> **Additional** Also, when Linking CXX shared library ../libembree3.dylib, it report a lot of warnings like:
> 
> ```
> ld: warning: cannot export hidden symbol void embree::TaskScheduler::g_instance from ../libtasking.a(taskschedulerinternal.cpp.o)
> ```
> 
> I have no idea if this will have a bad influence in future running.

Don't worry. It won't.

**Comment by why986** [comment]
Ok. Now I am able to build the project successfully. Thanks for your help!

**Comment by odil24** [comment]
> Ok. Now I am able to build the project successfully. Thanks for your help!

Hi.If you can plz post here your build.

**Comment by Mike-Leo-Smith** [comment]
> > Ok. Now I am able to build the project successfully. Thanks for your help!
> 
> Hi.If you can plz post here your build.

Do you mean the binaries built for M1 Macs?

**Comment by odil24** [comment]
> > > Ok. Now I am able to build the project successfully. Thanks for your help!
> > 
> > 
> > Hi.If you can plz post here your build.
> 
> Do you mean the binaries built for M1 Macs?

No, I meant released build for Win10 for testing purposes (I'm not familiar with source building)

**Comment by Mike-Leo-Smith** [comment]
> No, I meant released build for Win10 for testing purposes (I'm not familiar with source building)

Hi, @odil24 

I have set up the GitHub Actions to automatically upload the built artifacts. Please visit the `Actions` tab of the repo, click a recent successful workflow run, and scroll until the bottom of the page to view the artifacts and download a desired one. 

For Windows 10/11, you might want the one tagged [`windows-2022-Release-cl`](https://github.com/LuisaGroup/LuisaRender/suites/10111377069/artifacts/493280056).

**Comment by Mike-Leo-Smith** [comment]
To run the program, please take the following steps:
- unzip the downloaded archive;
- open a terminal and `cd` into the extracted folder;
- run `./luisa-render-cli -b <backend> <path-to-scene-file>`.

For Windows builds, available backends are `dx` and `cuda`. You would need an RTX-enabled graphics card and a recent driver installed. To download a demo scene, please see the `README.md` of the repo.
