### ISSUE TITLE
Is there any documentation for this project?

### ISSUE THREAD

**Issue by why986** [LuisaGroup/LuisaRender#9]
I want to implement an environment camera or a fisheye camera model under LuisaRender, but I am confused about the camera model of LuisaRender.
 So I want to ask for a documentation of the camera model (I have already read pbrt documentation but LuisaRender seems a bit different), or some advice for me to implement a new camera model. 
Thanks for your help!

**Comment by Mike-Leo-Smith** [comment]
Hi, @why986 

To implement a new camera, you would need to create a new plug-in and override the following abstract method in the base `Camera` class:
```cpp
[[nodiscard]] virtual std::pair<Var<Ray>, Float /* weight, typically set to 1 */>
_generate_ray_in_camera_space(Expr<float2> pixel /* the pixel on the film, with the upper left pixel being (0, 0), lower right (width, height) */,
                                  Expr<float2> u_lens /* 2D uniform random number for lens sampling */,
                                  Expr<float> time /* time, possibly for temporal effects */) const noexcept = 0;
```
which is responsible for generating a ray in the camera space. The base `Camera` class will invoke the overridden implementation and handle other things (e.g., filter sampling, camera transform).

The camera space is a right-handed orthogonal space, with the camera at the origin, the x-axis pointing to the right, y up, and z backward. For example, a ray from the camera to the center of the film will be `origin = (0, 0, 0), direction = (0, 0, -1)`.

**Comment by why986** [comment]
Hi, @Mike-Leo-Smith 
Thanks for your instruction! I will have a try on it.
